version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80" 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000" 
    depends_on:
      - mysql 
    environment:
      DB_HOST: mysql 
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: devnet

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: devnet    
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql 

volumes:
  mysql-data:
